name 'blacksquarelabs-yum'
maintainer 'John Coleman'
maintainer_email 'chef@blacksquarelabs.com'
license 'Apache 2.0'
description 'Installs/Configures blacksquarelabs-yum'
long_description 'Installs/Configures blacksquarelabs-yum'
version '0.2.2'
depends 'yum', '= 3.8.2'
